# Generated by Django 4.0.4 on 2022-05-30 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=5000)),
                ('types', models.CharField(max_length=100)),
            ],
        ),
    ]
