# Generated by Django 4.0.4 on 2022-06-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_projects_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='fork',
            field=models.CharField(default='NA', max_length=200),
            preserve_default=False,
        ),
    ]
