# Generated by Django 4.0.4 on 2022-06-05 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_projects_fork'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='project',
        ),
    ]
